services:
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - 16379:6379
    command : redis-server
    networks:
      - a_network

  mariadb_container:
    container_name: mariadb_container
    image: mariadb
    ports:
      - 13306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      - TZ= Asia/Seoul
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=hotels_db
      - MARIADB_USER=hotels_user
      - MARIADB_PASSWORD=hotels12345
    networks:
      - a_network
  #    restart: always

  boot-app:
    image: seojw173/back_image:1.0.1
    # image: jhh0101/back_image
    container_name: boot_container
    ports:
      - 18888:8085
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb_container:3306/hotels_db
      - SPRING_DATASOURCE_USERNAME=hotels_user
      - SPRING_DATASOURCE_PASSWORD=hotels12345
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - mariadb_container

    networks:
      - a_network
#    restart: always

networks:
  a_network:
    driver: bridge